user:
  id: 1
  username: "xiaofang"
  gender: false
  birthday: "2000-10-10"
  hobbies: ["唱歌","跳舞"]
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_exam
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

